#pragma once

#define BLUESHIFT_VERSION_MAJOR 0
#define BLUESHIFT_VERSION_MINOR 4
#define BLUESHIFT_VERSION_PATCH 0
#define BLUESHIFT_VERSION_SUFFIX "dev"

#define BLUESHIFT_VERSION_STRING "0.4.0-dev"

#ifndef BLUESHIFT_BUILD_TYPE_DEBUG
#define BLUESHIFT_BUILD_TYPE_DEBUG 0
#endif
